package com.datio.sas.model

import org.apache.spark.sql.types._

object Schemas {

  def vsfmapob: StructType = StructType(Seq(
    StructField("COD_PAISOALF", StringType),
    StructField("COD_ENTALFA", StringType),
    StructField("COD_IDCONTRA", StringType),
    StructField("COD_TREC", StringType),
    StructField("COD_PAISOCLI", StringType),
    StructField("COD_ENTALCLI", StringType),
    StructField("COD_PERSCTPN", StringType),
    StructField("FEC_CIERRE", StringType),
    StructField("COD_BANCSB", StringType),
    StructField("COD_OFICI", StringType),
    StructField("COD_CCONTR", StringType),
    StructField("COD_CFOLIO", StringType),
    StructField("COD_DPEN", StringType),
    StructField("COD_ANO", StringType),
    StructField("COD_MES", StringType),
    StructField("COD_PERSONA", StringType),
    StructField("COD_AREANEGO", StringType),
    StructField("COD_CTGCOM", StringType),
    StructField("COD_AGRCOM", StringType),
    StructField("COD_SUBAGR", StringType),
    StructField("COD_EPIGSF4", StringType),
    StructField("COD_PRODCAT", StringType),
    StructField("COD_CATDCAT", StringType),
    StructField("XTI_ESTADO", StringType),
    StructField("FAP_A", StringType),
    StructField("FOP_APUZ", StringType),
    StructField("IMP_APUZM", FloatType),
    StructField("IMP_APUZT", FloatType),
    StructField("IMP_APUZA", FloatType),
    StructField("IMP_DEVZA", FloatType),
    StructField("IMP_DEVZM", FloatType),
    StructField("IMP_DEVZT", FloatType),
    StructField("QTY_APUZA", IntegerType),
    StructField("QTY_APUZM", IntegerType),
    StructField("QTY_APUZT", IntegerType),
    StructField("QNU_DEVZA", IntegerType),
    StructField("QNU_DEVZM", IntegerType),
    StructField("QNU_DEVZT", IntegerType),
    StructField("QTY_MESAPUZA", IntegerType),
    StructField("COD_OFIALFA", StringType),
    StructField("TIM_FMODIFIC", StringType)
  )
  )

  def vsfmahss: StructType = StructType(Seq(
    StructField("COD_PAISOALF", StringType),
    StructField("COD_ENTALFA", StringType),
    StructField("COD_IDCONTRA", StringType),
    StructField("FEC_CIERRE", StringType),
    StructField("COD_BANCSB", StringType),
    StructField("COD_OFICI", StringType),
    StructField("COD_CCONTR", StringType),
    StructField("COD_CFOLIO", StringType),
    StructField("COD_DPEN", StringType),
    StructField("COD_ANO", StringType),
    StructField("COD_MES", StringType),
    StructField("COD_BANORIGN", StringType),
    StructField("COD_OFICON", StringType),
    StructField("COD_PAISOCLI", StringType),
    StructField("COD_ENTALCLI", StringType),
    StructField("COD_AREANEGO", StringType),
    StructField("COD_PERSONA", StringType),
    StructField("COD_IDEFISCA", StringType),
    StructField("COD_REMESART", StringType),
    StructField("COD_CANAL_DV", StringType),
    StructField("COD_GESCONT", StringType),
    StructField("COD_CTGCOM", StringType),
    StructField("COD_AGRCOM", StringType),
    StructField("COD_PRODCAT", StringType),
    StructField("COD_CATDCAT", StringType),
    StructField("FAP_CONTR", StringType),
    StructField("XTI_ESTADO", StringType),
    StructField("IMP_CESTELZM", FloatType),
    StructField("IMP_CESTELZT", FloatType),
    StructField("IMP_CESTELZA", FloatType),
    StructField("QNU_CESTELZM", StringType),
    StructField("QNU_CESTELZT", StringType),
    StructField("QNU_CESTELZA", StringType),
    StructField("IMP_CESDOMZM", FloatType),
    StructField("IMP_CESDOMZT", FloatType),
    StructField("IMP_CESDOMZA", FloatType),
    StructField("QNU_CESDOMZM", StringType),
    StructField("QNU_CESDOMZT", StringType),
    StructField("QNU_CESDOMZA", StringType),
    StructField("IMP_CESNDOZM", FloatType),
    StructField("IMP_CESNDOZT", FloatType),
    StructField("IMP_CESNDOZA", FloatType),
    StructField("QNU_CESNDOZM", StringType),
    StructField("QNU_CESNDOZT", StringType),
    StructField("QNU_CESNDOZA", StringType),
    StructField("IMP_CESTRZM", FloatType),
    StructField("IMP_CESTRZT", FloatType),
    StructField("IMP_CESTRZA", FloatType),
    StructField("QNU_CESTRZM", StringType),
    StructField("QNU_CESTRZT", StringType),
    StructField("QNU_CESTRZA", StringType),
    StructField("IMP_ANULAM", FloatType),
    StructField("IMP_ANULAT", FloatType),
    StructField("IMP_ANULAA", FloatType),
    StructField("QTY_ANULAM", StringType),
    StructField("QTY_ANULAT", StringType),
    StructField("QTY_ANULAA", StringType),
    StructField("IMP_RECANUM", FloatType),
    StructField("IMP_RECANUT", FloatType),
    StructField("IMP_RECANUA", FloatType),
    StructField("QTY_RECANUM", StringType),
    StructField("QTY_RECANUT", StringType),
    StructField("QTY_RECANUA", StringType),
    StructField("IMP_ACTIVOZM", FloatType),
    StructField("IMP_ACTIVOZA", FloatType),
    StructField("IMP_PASIVOZM", FloatType),
    StructField("IMP_PASIVOZA", FloatType),
    StructField("IMP_TCERABZM", FloatType),
    StructField("IMP_TCERABZA", FloatType),
    StructField("IMP_BENFABZM", FloatType),
    StructField("IMP_BENFABZA", FloatType),
    StructField("IMP_BENAABZM", FloatType),
    StructField("IMP_BENAABZA", FloatType),
    StructField("IMP_MINTABZM", FloatType),
    StructField("IMP_MINTABZA", FloatType),
    StructField("IMP_SERVABZM", FloatType),
    StructField("IMP_SERVABZA", FloatType),
    StructField("IMP_MOPEABZM", FloatType),
    StructField("IMP_MOPEABZA", FloatType),
    StructField("IMP_COSTABZM", FloatType),
    StructField("IMP_COSTABZA", FloatType),
    StructField("IMP_MNETABZM", FloatType),
    StructField("IMP_MNETABZA", FloatType),
    StructField("COD_OFIALFA", StringType),
    StructField("COD_PERSCTPN", StringType),
    StructField("TIM_FMODIFIC", StringType)
  )
  )

  def getSchema(name: String): StructType = {
    name match {
      case "vsfmapob" => vsfmapob
      case "vsfmahss" => vsfmahss
    }
  }
}